# This file was generated by GoReleaser. DO NOT EDIT.
cask "noema" do
  version "0.9.2"

  on_macos do
    on_intel do
      url "https://github.com/Fail-Safe/Noema/releases/download/v#{version}/noema_#{version}_darwin_amd64.tar.gz"
      sha256 "15453ed7340bae0f85034fc5d3cb2b559da99d5a028d420e3de901b31c5fdc5d"
    end
    on_arm do
      url "https://github.com/Fail-Safe/Noema/releases/download/v#{version}/noema_#{version}_darwin_arm64.tar.gz"
      sha256 "ef9a0fb1acb8416ba1d3282813c5bdcfac578efe9ce3953c74a3aed2e64890ee"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Fail-Safe/Noema/releases/download/v#{version}/noema_#{version}_linux_amd64.tar.gz"
      sha256 "3ab250c9ef9d1d07abad4adfe0fa20f55dc3deff511addc4486cc9218bd7954f"
    end
    on_arm do
      url "https://github.com/Fail-Safe/Noema/releases/download/v#{version}/noema_#{version}_linux_arm64.tar.gz"
      sha256 "f222eb5c6c2adc7429a3424345dd59f42d6e18542d0a5409686c09b4bc029ea0"
    end
  end

  name "noema"
  desc "The intentional memory layer for your AI agents"
  homepage "https://github.com/Fail-Safe/Noema"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "noema"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/noema"]
    end
  end

  # No zap stanza required

end
