# This file was generated by GoReleaser. DO NOT EDIT.
cask "noema" do
  version "0.9.3"

  on_macos do
    on_intel do
      url "https://github.com/Fail-Safe/Noema/releases/download/v#{version}/noema_#{version}_darwin_amd64.tar.gz"
      sha256 "a301fc10571b7cfe6c91b24ae8a832bc189425571de799a6a35363545d19dbdf"
    end
    on_arm do
      url "https://github.com/Fail-Safe/Noema/releases/download/v#{version}/noema_#{version}_darwin_arm64.tar.gz"
      sha256 "f7633333d4670424c6e2abae48fb16deef3240b3038fcb1e548feb5428fb9905"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Fail-Safe/Noema/releases/download/v#{version}/noema_#{version}_linux_amd64.tar.gz"
      sha256 "200cf8a11b8ce3af9c375719df054b2210f2990238d510a193960d17afda4059"
    end
    on_arm do
      url "https://github.com/Fail-Safe/Noema/releases/download/v#{version}/noema_#{version}_linux_arm64.tar.gz"
      sha256 "a16b31f54b9f76f44602cc016ef449d2a8e1654f9f043cd550f9467e7d65d8ff"
    end
  end

  name "noema"
  desc "The intentional memory layer for your AI agents"
  homepage "https://github.com/Fail-Safe/Noema"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "noema"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/noema"]
    end
  end

  # No zap stanza required

end
