# This file was generated by GoReleaser. DO NOT EDIT.
cask "noema" do
  version "0.6.0"

  on_macos do
    on_intel do
      url "https://github.com/Fail-Safe/Noema/releases/download/v#{version}/noema_#{version}_darwin_amd64.tar.gz"
      sha256 "d635d3bec189cec803552aabf5a7c9079bbf366d203c303be7a1d8f6c5b7cada"
    end
    on_arm do
      url "https://github.com/Fail-Safe/Noema/releases/download/v#{version}/noema_#{version}_darwin_arm64.tar.gz"
      sha256 "9652673bae571ca1708a7334b8ab0457bee9d8943c9c7d1dcd598ed84d91a1e1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Fail-Safe/Noema/releases/download/v#{version}/noema_#{version}_linux_amd64.tar.gz"
      sha256 "3c9063f8e44ddb1546eca5600d4d534b334b383414730954417c1a8534962f05"
    end
    on_arm do
      url "https://github.com/Fail-Safe/Noema/releases/download/v#{version}/noema_#{version}_linux_arm64.tar.gz"
      sha256 "a504eac2942b2287607e545be6a6d89c62d778335d4e93d382d25aea1f42bbca"
    end
  end

  name "noema"
  desc "The intentional memory layer for your AI agents"
  homepage "https://github.com/Fail-Safe/Noema"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "noema"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/noema"]
    end
  end

  # No zap stanza required

end
