# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NoemaBeta < Formula
  desc "The intentional memory layer for your AI agents (beta channel)"
  homepage "https://github.com/Fail-Safe/Noema"
  version "0.10.0-beta.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.10.0-beta.2/noema_0.10.0-beta.2_darwin_amd64.tar.gz"
      sha256 "8795549ee48ccb57dc2185ad5ea1cc8990fe0592aee280f76eac27008939f5d2"

      define_method(:install) do
        bin.install "noema"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.10.0-beta.2/noema_0.10.0-beta.2_darwin_arm64.tar.gz"
      sha256 "e1c5e13646217fd99531ec0e53d4a74befeb46833bc63f1a8754690f104331c4"

      define_method(:install) do
        bin.install "noema"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.10.0-beta.2/noema_0.10.0-beta.2_linux_amd64.tar.gz"
      sha256 "708f5a53e38607d5d68765f8b16d48430a6120b4a30bf34f5f8b81d3578a392a"
      define_method(:install) do
        bin.install "noema"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.10.0-beta.2/noema_0.10.0-beta.2_linux_arm64.tar.gz"
      sha256 "aa46020538875ebcd45a4f8be118d1eb91010a4dcb7448d1c0c68b3b05d44b33"
      define_method(:install) do
        bin.install "noema"
      end
    end
  end

  conflicts_with "noema"

  test do
    system "#{bin}/noema", "version"
  end
end
