# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Noema < Formula
  desc "The intentional memory layer for your AI agents"
  homepage "https://github.com/Fail-Safe/Noema"
  version "0.9.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.9.1/noema_0.9.1_darwin_amd64.tar.gz"
      sha256 "873c8b170e68d64b072285dd14ad39fdeab0fc18931c71cbc51b90d27f786a3f"

      define_method(:install) do
        bin.install "noema"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.9.1/noema_0.9.1_darwin_arm64.tar.gz"
      sha256 "e652b800283be5dd48a843b0687c935744588b2076fcd38fe12a139c2b52c3e4"

      define_method(:install) do
        bin.install "noema"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.9.1/noema_0.9.1_linux_amd64.tar.gz"
      sha256 "7f988c50844ee2cfc6d6ab8034b6c5ecf33b8b7d06309150524a44de6cec203a"
      define_method(:install) do
        bin.install "noema"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.9.1/noema_0.9.1_linux_arm64.tar.gz"
      sha256 "93fe53f0c0d0106b1187280f4c8ea82c83c93a5a5ecc5d8fe383289f470e9d39"
      define_method(:install) do
        bin.install "noema"
      end
    end
  end

  test do
    system "#{bin}/noema", "version"
  end
end
