# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Noema < Formula
  desc "The intentional memory layer for your AI agents"
  homepage "https://github.com/Fail-Safe/Noema"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.3.1/noema_0.3.1_darwin_amd64.tar.gz"
      sha256 "37ea0d468dafef16f98419bf5e4779d3e688ee0fdee54c4d939602b0f4fdfebe"

      define_method(:install) do
        bin.install "noema"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.3.1/noema_0.3.1_darwin_arm64.tar.gz"
      sha256 "93530f1de6a1a585e366fe9f77cc07886c289eb5694855d655d46d59b0d3f47d"

      define_method(:install) do
        bin.install "noema"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.3.1/noema_0.3.1_linux_amd64.tar.gz"
      sha256 "4096dd0521ad5ee6d5236166d3abcf30557ce6bb9722ee4c481f6d878c0df5fe"
      define_method(:install) do
        bin.install "noema"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Fail-Safe/Noema/releases/download/v0.3.1/noema_0.3.1_linux_arm64.tar.gz"
      sha256 "4e1da0ac19bb1f6caeae5544a4d3a4a8232c660f1303adcc4d6aa70554d0c144"
      define_method(:install) do
        bin.install "noema"
      end
    end
  end

  test do
    system "#{bin}/noema", "version"
  end
end
